'use client';

import { CalendarDays, ChevronLeft, ChevronRight, Plus, Trash2 } from 'lucide-react';
import { useEffect, useMemo, useState } from 'react';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Checkbox } from '@/components/ui/checkbox';

type Task = { id: number; title: string; taskDate: string; time?: string; category: 'work' | 'fitness' | 'food' | 'personal'; priority: string; done: boolean };
const today = new Date().toLocaleDateString('sv-SE');
const labels = { work: '开发', fitness: '健身', food: '饮食', personal: '个人' };

export function DailyPlanner({ onAdd }: { onAdd: (date: string) => void }) {
  const [selected, setSelected] = useState(today); const [month, setMonth] = useState(() => new Date(`${today}T12:00:00`)); const [tasks, setTasks] = useState<Task[]>([]); const [loading, setLoading] = useState(true);
  const load = () => { setLoading(true); fetch(`/api/tasks?date=${selected}`).then((response) => response.json()).then((data) => setTasks(data as Task[])).catch(() => undefined).finally(() => setLoading(false)); };
  useEffect(load, [selected]);
  const cells = useMemo(() => monthCells(month), [month]);
  const choose = (date: Date) => { const value = date.toLocaleDateString('sv-SE'); setSelected(value); setMonth(new Date(date.getFullYear(), date.getMonth(), 1)); };
  const moveMonth = (offset: number) => setMonth(new Date(month.getFullYear(), month.getMonth() + offset, 1));
  const toggle = async (task: Task) => { setTasks((current) => current.map((item) => item.id === task.id ? { ...item, done: !item.done } : item)); await fetch('/api/tasks', { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ id: task.id, done: !task.done }) }); window.dispatchEvent(new Event('tasks-updated')); };
  const remove = async (id: number) => { setTasks((current) => current.filter((item) => item.id !== id)); await fetch(`/api/tasks?id=${id}`, { method: 'DELETE' }); window.dispatchEvent(new Event('tasks-updated')); };
  return <div className="grid gap-4 xl:grid-cols-[300px_minmax(0,1fr)]"><article className="panel h-fit p-5"><div className="flex items-center justify-between"><Button variant="ghost" size="icon-sm" onClick={() => moveMonth(-1)}><ChevronLeft /></Button><h2 className="text-sm font-semibold">{month.getFullYear()}年{month.getMonth() + 1}月</h2><Button variant="ghost" size="icon-sm" onClick={() => moveMonth(1)}><ChevronRight /></Button></div><div className="mt-4 grid grid-cols-7 gap-1 text-center text-xs text-muted-foreground">{['一','二','三','四','五','六','日'].map((day) => <span key={day} className="py-2">{day}</span>)}{cells.map((cell) => { const value = cell.date.toLocaleDateString('sv-SE'); return <button key={value} onClick={() => choose(cell.date)} className={`aspect-square rounded-lg text-xs transition hover:bg-muted ${value === selected ? 'bg-primary font-semibold text-primary-foreground hover:bg-primary' : ''} ${!cell.current ? 'text-muted-foreground/35' : ''}`}>{cell.date.getDate()}</button>; })}</div><Button className="mt-4 w-full" variant="outline" size="sm" onClick={() => choose(new Date())}>回到今天</Button></article><article className="panel overflow-hidden"><div className="flex items-center justify-between border-b px-6 py-4"><div><h2 className="font-semibold">{formatDate(selected)}</h2><p className="mt-1 text-xs text-muted-foreground">{tasks.filter((task) => task.done).length}/{tasks.length} 已完成</p></div><Button size="sm" onClick={() => onAdd(selected)}><Plus />添加事项</Button></div><div className="divide-y">{loading ? <div className="px-6 py-14 text-center text-sm text-muted-foreground">正在读取计划…</div> : tasks.length === 0 ? <div className="px-6 py-16 text-center"><div className="mx-auto grid size-12 place-items-center rounded-2xl bg-primary/10 text-primary"><CalendarDays className="size-5" /></div><h3 className="mt-4 text-sm font-semibold">这一天还没有计划</h3><p className="mt-1 text-xs text-muted-foreground">可以提前安排未来，也可以补充过去的记录。</p><Button className="mt-5" variant="outline" size="sm" onClick={() => onAdd(selected)}><Plus />添加计划</Button></div> : tasks.map((task) => <div key={task.id} className="group flex items-center gap-3 px-6 py-4 hover:bg-muted/30"><Checkbox checked={task.done} onCheckedChange={() => toggle(task)} /><div className="min-w-0 flex-1"><p className={`truncate text-sm font-medium ${task.done ? 'text-muted-foreground line-through' : ''}`}>{task.title}</p><div className="mt-1 flex items-center gap-2 text-xs text-muted-foreground"><span>{task.time || '普通待办'}</span><Badge variant="secondary">{labels[task.category]}</Badge></div></div><Button variant="ghost" size="icon-sm" className="opacity-0 group-hover:opacity-100" onClick={() => remove(task.id)}><Trash2 /></Button></div>)}</div></article></div>;
}

function monthCells(month: Date) { const first = new Date(month.getFullYear(), month.getMonth(), 1); const startOffset = (first.getDay() + 6) % 7; const start = new Date(month.getFullYear(), month.getMonth(), 1 - startOffset); return Array.from({ length: 42 }, (_, index) => { const date = new Date(start); date.setDate(start.getDate() + index); return { date, current: date.getMonth() === month.getMonth() }; }); }
function formatDate(value: string) { return new Intl.DateTimeFormat('zh-CN', { year: 'numeric', month: 'long', day: 'numeric', weekday: 'long' }).format(new Date(`${value}T12:00:00`)); }
