import { env } from 'cloudflare:workers';
import { ensureDatabase } from '@/db/initialize';
import { PrintButton } from './print-button';

type Row = Record<string, unknown>;
export default async function ReportPage() {
  await ensureDatabase(); const [tasks, projects, workouts, meals] = await env.DB.batch([
    env.DB.prepare('SELECT * FROM tasks WHERE deleted_at IS NULL ORDER BY task_date DESC, start_time'),
    env.DB.prepare('SELECT * FROM projects WHERE deleted_at IS NULL ORDER BY id DESC'),
    env.DB.prepare('SELECT * FROM workouts WHERE deleted_at IS NULL ORDER BY workout_date DESC'),
    env.DB.prepare('SELECT * FROM meals WHERE deleted_at IS NULL ORDER BY meal_date DESC'),
  ]);
  const taskRows = tasks.results as Row[]; const mealRows = meals.results as Row[];
  return <main className="report mx-auto max-w-5xl bg-white px-8 py-10 text-slate-900 sm:px-12"><div className="no-print mb-8 flex justify-end"><PrintButton /></div><header className="border-b-2 border-emerald-700 pb-6"><p className="text-sm font-semibold text-emerald-700">PERSONAL WORKSPACE</p><h1 className="mt-2 text-3xl font-bold">个人工作台综合报告</h1><p className="mt-2 text-sm text-slate-500">生成时间：{new Date().toLocaleString('zh-CN')}</p></header><section className="mt-8 grid grid-cols-4 gap-3"><Metric value={String(taskRows.filter((row) => row.done).length)} label="完成计划" /><Metric value={String(projects.results.length)} label="开发项目" /><Metric value={String(workouts.results.length)} label="训练记录" /><Metric value={`${Math.round(mealRows.reduce((sum, row) => sum + Number(row.calories || 0), 0))}`} label="记录热量 kcal" /></section><ReportSection title="每日计划" headers={['日期','事项','时间','模块','状态']} rows={taskRows.map((row) => [row.task_date,row.title,[row.start_time,row.end_time].filter(Boolean).join('-') || '普通待办',row.category,row.done ? '已完成' : '待完成'])} /><ReportSection title="开发项目" headers={['项目','说明','进度','状态']} rows={(projects.results as Row[]).map((row) => [row.name,row.description,`${row.manual_progress ?? row.progress ?? 0}%`,row.status])} /><ReportSection title="健身记录" headers={['日期','训练','时长','状态']} rows={(workouts.results as Row[]).map((row) => [row.workout_date,row.name,`${row.duration || 0} 分钟`,row.completed ? '已完成' : '未完成'])} /><ReportSection title="饮食记录" headers={['日期','餐食','热量','蛋白质','碳水','脂肪']} rows={mealRows.map((row) => [row.meal_date,row.name,`${row.calories || 0} kcal`,`${row.protein || 0}g`,`${row.carbs || 0}g`,`${row.fat || 0}g`])} /><footer className="mt-12 border-t pt-4 text-center text-xs text-slate-400">个人工作台 · 数据仅保存在本地</footer></main>;
}
function Metric({ value, label }: { value: string; label: string }) { return <div className="rounded-xl bg-emerald-50 p-4"><strong className="text-2xl text-emerald-800">{value}</strong><p className="mt-1 text-xs text-slate-500">{label}</p></div>; }
function ReportSection({ title, headers, rows }: { title: string; headers: string[]; rows: unknown[][] }) { return <section className="mt-9 break-inside-avoid"><h2 className="mb-3 text-lg font-bold">{title}</h2><table className="w-full table-fixed border-collapse text-left text-xs"><thead><tr className="bg-emerald-700 text-white">{headers.map((header) => <th key={header} className="border border-emerald-800 px-3 py-2">{header}</th>)}</tr></thead><tbody>{rows.length ? rows.map((row, index) => <tr key={index} className="even:bg-slate-50">{row.map((value, cell) => <td key={cell} className="border border-slate-200 px-3 py-2 align-top break-words">{String(value ?? '')}</td>)}</tr>) : <tr><td className="border border-slate-200 px-3 py-5 text-center text-slate-400" colSpan={headers.length}>暂无数据</td></tr>}</tbody></table></section>; }
